apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influx-storage
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb
  labels:
    app: influxdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: influxdb
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      containers:
        - name: influxdb
          imagePullPolicy: Never
          image: influxdb
          ports:
          - containerPort: 8086
          volumeMounts:
            - mountPath: /var/lib/influxdb
              name: influx-storage-p
      volumes:
            - name: influx-storage-p
              persistentVolumeClaim:
                claimName: influx-storage
---

apiVersion: v1 
kind: Service
metadata:
  name: influx-svc
  labels:
    app: influxdb
spec:
  type: ClusterIP
  clusterIP: 10.99.99.98
  selector:
    app: influxdb
  ports:
  - name: influxdb
    protocol: TCP
    port: 8086
    targetPort: 8086